spring:
  application:
    name: store
  datasource:
    url: jdbc:mysql://localhost:3307/store?createDatabaseIfNotExist=true
    username: root
    password: 2264
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
stripe:
  apiUrl: https://api.stripe.com
  enabled: true
  timeout: 3000
  supportedCurrencies: USD,EUR,GBP
paypal:
  apiUrl: https://api.paypal.com
  enabled: true
  timeout: 3000
  supportedCurrencies: USD,EUR,GBP
email:
  serviceUrl: https://api.emailservice.com
  host: smtp.example.com
  port: 587
notification:
  serviceUrl: https://api.notificationservice.com
sms:
  serviceUrl: https://api.smsservice.com
payment-service: paypal
