ALTER TABLE `wishlist` 
ADD COLUMN `id` BIGINT NOT NULL AUTO_INCREMENT FIRST,
ADD COLUMN `added_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`id`),
ADD UNIQUE KEY `uk_user_product` (`user_id`, `product_id`);
